
[2020-04-14 18:38:04] Traceback (most recent call last):
  File "load_handler.pyx", line 86, in cefpython_py37.LoadHandler_OnLoadError
  File "f:\Users\Sebastien\Documents\GitHub\CEFPython_tutorial\CEFApp\cef_app.py", line 15, in OnLoadError
    parsed_url = urlparse(failed_url)
NameError: name 'urlparse' is not defined


[2020-04-14 18:42:46] Traceback (most recent call last):
  File "f:/Users/Sebastien/Documents/GitHub/CEFPython_tutorial/CEFApp/main.py", line 22, in <module>
    MyApp().run()
  File "f:/Users/Sebastien/Documents/GitHub/CEFPython_tutorial/CEFApp/main.py", line 19, in __init__
    CEFApp.__init__(self, "jinja://"+"helloworld.jinja2" ,window_title="MyApp", jinja_env = JINJA_ENV)
  File "f:\Users\Sebastien\Documents\GitHub\CEFPython_tutorial\CEFApp\cef_app.py", line 62, in __init__
    self.cef_temp_dir = os.path.join(os.path.dirname(__file__), ".cef_temp")
NameError: name 'os' is not defined


[2020-04-14 18:46:47] Traceback (most recent call last):
  File "load_handler.pyx", line 86, in cefpython_py37.LoadHandler_OnLoadError
  File "f:\Users\Sebastien\Documents\GitHub\CEFPython_tutorial\CEFApp\cef_app.py", line 20, in OnLoadError
    query_data = dict(parsed_url.query.split("="))
ValueError: dictionary update sequence element #0 has length 4; 2 is required


[2020-04-14 18:47:14] Traceback (most recent call last):
  File "load_handler.pyx", line 86, in cefpython_py37.LoadHandler_OnLoadError
  File "f:\Users\Sebastien\Documents\GitHub\CEFPython_tutorial\CEFApp\cef_app.py", line 21, in OnLoadError
    query_data = dict(parsed_url.query.split("="))
ValueError: dictionary update sequence element #0 has length 4; 2 is required


[2020-04-14 18:47:34] Traceback (most recent call last):
  File "load_handler.pyx", line 86, in cefpython_py37.LoadHandler_OnLoadError
  File "f:\Users\Sebastien\Documents\GitHub\CEFPython_tutorial\CEFApp\cef_app.py", line 21, in OnLoadError
    query_data = dict(tuple(parsed_url.query.split("=")))
ValueError: dictionary update sequence element #0 has length 4; 2 is required


[2020-04-14 18:48:03] Traceback (most recent call last):
  File "f:\Users\Sebastien\Documents\GitHub\CEFPython_tutorial\CEFApp\cef_app.py", line 25, in OnLoadError
    self.app.LoadJinjaUrl(path, context=query_data)
UnboundLocalError: local variable 'path' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "load_handler.pyx", line 86, in cefpython_py37.LoadHandler_OnLoadError
  File "f:\Users\Sebastien\Documents\GitHub\CEFPython_tutorial\CEFApp\cef_app.py", line 27, in OnLoadError
    print("Template not found",path)
UnboundLocalError: local variable 'path' referenced before assignment

